name: Format Code

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  pull_request:

jobs:
  format:
    name: Format code
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust the Node.js version as needed

    - name: Install dependencies
      run: npm install

    - name: Format code with Prettier
      run: npx prettier --write .
